### ISSUE TITLE
Editing symbols after application is launched is not allowed

### ISSUE THREAD

**Issue by mzilak** [cboard-org/cboard#790] opened 2020-09-03 14:13 UTC
Editing of symbols on the boards (existing or newly imported) is not allowed after the application is launched. Try to reproduce this in a way that you launch the app (before that the app was not in the recent apps), import some public board and try to edit the title of some symbol. The letters keep coming back. This I noticed only after the editing attempt after launching the app, after that editing works fine.

I tried to record the situation, the video recording is on this link: https://drive.google.com/file/d/1XB-kvPm7TpW7O9IcRYY6kWFDplzG8bEU/view?usp=sharing

**Comment by sylvansson** [comment] 2021-01-05 14:03
@martinbedouret I can look into this if you want.

**Comment by martinbedouret** [comment] 2021-01-06 12:21
@sylvansson Yes! Please go ahead. Take into consideration that this bug is maybe just reproducible in the Android app.

**Comment by sylvansson** [comment] 2021-01-06 23:48
@mzilak I personally cannot reproduce this issue in Android or my browser. Can you still reproduce it on your device? If so, could you tell us which version of the Cboard app you're using?

**Comment by mzilak** [comment] 2021-01-07 08:57
@sylvansson , yes, I just managed to reproduce it again, Cboard version 1.7.1, device Samsung Galaxy S20.
Maybe if you try to delete the data of the application from the device. I did this, logged in into Cboard, downloaded the public board and tried to edit the symbol. Letters keep coming back like in the upper video.

**Comment by sylvansson** [comment] 2021-01-07 14:10
Thank you! I'll look into it again.

**Comment by sylvansson** [comment] 2021-01-20 05:25
@martinbedouret I was able to reproduce the issue on my smartphone. I'm currently unable to run the project with Cordova to debug though, so this won't be fixed right away.

**Comment by martinbedouret** [comment] 2021-01-20 14:44
no worries @sylvansson , I can take a look.

**Closed as completed** 2021-02-17 00:19 UTC
Labels: bug
