### ISSUE TITLE
Cannot rotate the photo after I create a custom pane with my own photo

### ISSUE THREAD

**Issue by hanzhaogang** [cboard-org/cboard#881] opened 2021-04-10 14:07 UTC
iphone ios 14.4 safira browser.

**Comment by shayc** [comment] 2021-04-29 14:39
I assume you want to rotate an image after you upload it? If so I'm marking this as a feature request and not a bug since we don't have a capability to rotate images as of now.

**Comment by hanzhaogang** [comment] 2021-05-07 01:26
> I assume you want to rotate an image after you upload it? If so I'm marking this as a feature request and not a bug since we don't have a capability to rotate images as of now.

Yes， that's right， a new feature.

**Closed as completed** 2021-11-22 14:37 UTC
Labels: feature
